### ISSUE TITLE
a bug 

### ISSUE THREAD

**Issue by HW140701** [mmc1993/sformat#1]
The target is :

name= "Hello world"

but，I use the SFormat like this:

SFormat("name = "" {0}“” "，“Hello world”)，the final is:

name = Hello world

**Comment by mmc1993** [comment]
我看你的地区是上海, 那我先假设你能看懂中文吧...

先谢谢你用我的这个库.
这个库我写了有很多年了, 一直打算重新实现, 但是又没有明显的动机趋势我去重新实现, 哈哈.
在我的其他项目中, 这个库已经被改过很多次了, 只是没有及时更新到这个仓库.

你给出的案例中, 输出的结果其实是正确的.
你觉得 "" 等价于 \", 其实不是的.
在C/C++中, 只有\才有转义的作用, 而""其实是一个空字符串.

举个例子:
char str[] = """123""";
你可能以为这个str实际内容是 "123"\0, 长度是6.
但实际上, 这个str的内容是123\0, 长度为4.


对于 """123""" 的理解, 应该是 ""+ "123" + ""
看到了吗, 123前后加了两个空字符串, 所以它并没有改变.

对于这种常量字符串, C/C++有一个断行的技巧, 我猜你大概可能还不知道.
char str[] = "这是一段很长的文本"
                  "文本在这里断行了"
                  "但是没关系, 可以随意换行";
看到了吗, 这三行常量字符串其实在编译阶段会被组合成一行, 当你把这三行改成一行时, 你会发现, 跟你提供的案例相似.

**Comment by HW140701** [comment]
> 我看你的地区是上海, 那我先假设你能看懂中文吧...
> 
> 先谢谢你用我的这个库.
> 这个库我写了有很多年了, 一直打算重新实现, 但是又没有明显的动机趋势我去重新实现, 哈哈.
> 在我的其他项目中, 这个库已经被改过很多次了, 只是没有及时更新到这个仓库.
> 
> 你给出的案例中, 输出的结果其实是正确的.
> 你觉得 "" 等价于 ", 其实不是的.
> 在C/C++中, 只有\才有转义的作用, 而""其实是一个空字符串.
> 
> 举个例子:
> char str[] = """123""";
> 你可能以为这个str实际内容是 "123"\0, 长度是6.
> 但实际上, 这个str的内容是123\0, 长度为4.
> 
> 对于 """123""" 的理解, 应该是 ""+ "123" + ""
> 看到了吗, 123前后加了两个空字符串, 所以它并没有改变.
> 
> 对于这种常量字符串, C/C++有一个断行的技巧, 我猜你大概可能还不知道.
> char str[] = "这是一段很长的文本"
> "文本在这里断行了"
> "但是没关系, 可以随意换行";
> 看到了吗, 这三行常量字符串其实在编译阶段会被组合成一行, 当你把这三行改成一行时, 你会发现, 跟你提供的案例相似.

我看的有点懵，那么正确的写法是什么？

**Comment by mmc1993** [comment]
SFormat("name = \"{0}\”"，“Hello world”);

**Comment by HW140701** [comment]
Got it ! Ths




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "mmc1993"<notifications@github.com&gt;; 
发送时间: 2020年8月20日(星期四) 下午4:51
收件人: "mmc1993/sformat"<sformat@noreply.github.com&gt;; 
抄送: "StubbornHuang"<623256052@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [mmc1993/sformat] a bug  (#1)





 
SFormat("name = "{0}\”"，“Hello world”);

**Comment by HW140701** [comment]
> SFormat("name = "{0}\”"，“Hello world”);

我试了你这个，发现不对，我修改了一下，下面的是对的：
SFormat("name =\"{0}\" "，“Hello world”);

**Comment by HW140701** [comment]
> > SFormat("name = "{0}\”"，“Hello world”);
> 
> 我试了你这个，发现不对，我修改了一下，下面的是对的：
> SFormat("name ="{0}" "，“Hello world”);

这个反斜杆被Github干掉了，正确的应该是：
SFormat("name =反斜杠"{0}反斜杠" "，“Hello world”);

**Comment by mmc1993** [comment]
SFormat("name =反斜杠"{0}反斜杠" "，“Hello world”);
我发的就是这个, 反斜杠被干掉了, 你看不到..

**Comment by HW140701** [comment]
> SFormat("name =反斜杠"{0}反斜杠" "，“Hello world”);
> 我发的就是这个, 反斜杠被干掉了, 你看不到..

OK ths
